version: '3.8'

services:
  app:
    build: .
    container_name: note-ton-tacos
    restart: unless-stopped
    ports:
      - "8000:3000" # Expose le site sur le port 8000
    volumes:
      # On crée un bind mount pour que la base de données SQLite ne soit pas perdue si on supprime le container
      - ./backend/tacos.sqlite:/usr/src/app/backend/tacos.sqlite
    environment:
      - NODE_ENV=production
