version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: tacos_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: tacos
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: tacos_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_USER=admin
      - DB_HOST=db
      - DB_NAME=tacos
      - DB_PASSWORD=password123
      - DB_PORT=5432
    volumes:
      - ./backend:/usr/src/app/backend
      - ./frontend:/usr/src/app/frontend
#    command: npm run dev
    depends_on:
      - db

volumes:
  pgdata:
